version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-osc
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    env_file:
      - .env.mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - osc-mysql-volume:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/00-init.sql
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./data.sql:/docker-entrypoint-initdb.d/02-data.sql
      - ./auth_schema.sql:/docker-entrypoint-initdb.d/03-schema.sql
      - ./auth_data.sql:/docker-entrypoint-initdb.d/04-data.sql
    networks:
      - osc-network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-osc
    env_file:
      - .env.rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    restart: unless-stopped
    volumes:
      - osc-rabbitmq-data:/var/lib/rabbitmq
    networks:
      - osc-network


networks:
  osc-network:
    driver: bridge

volumes:
  osc-mysql-volume:
  osc-rabbitmq-data: