GET http://localhost:9000/actuator/prometheus
Authorization: Bearer eyJraWQiOiJjYzk2MDk4OS0yN2Q5LTQ3ZTUtYTI5My02MTY5Njk3ZmEwN2IiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJwcm9tZXRoZXVzIiwiYXVkIjoicHJvbWV0aGV1cyIsIm5iZiI6MTc1MDYxMTAxNCwic2NvcGUiOlsiYWN0dWF0b3I6cmVhZCJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwOTAiLCJleHAiOjE3NTA2MTQ2MTQsImlhdCI6MTc1MDYxMTAxNCwianRpIjoiMjM4Y2M3MmYtNjFjNC00ZTliLTk5NzAtZjA5M2QwZGUyZTgyIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9TRVJWSUNFIl19.QMZqP_9lOL89_k7hfYkid-kNcc7JB2MPFGbsDEGwcY0sSvkNA40dMxWM6T-Im1BzgXwS4gqbwxv5Rs0egwczuSCD3Othyl28D-dRsA2v08-vzZzuuwgwE-D_kAABNvEmvteoKnz0viu955FY2s6qc9-64N-tnxJeqdtw8ByjfAtDcqLWTvIHmAMV0hFqXakR3AnGdgOMKMgOBRYXZqlpmdJd9PKAcxms7g3uorV5BMDH5LjR-lray30wtmvxSoiSYgaC_mYzmPURxF0r2VN3f2WQzN_86wGAf3Uvcl_mdA-yzIonuLoBlUs6tIK5I_ypcnZq4xoYKSdqrt8dbMkGfw
Accept: text/plain