# Получение Jwt-Токена (ROLE_SERVICE, SCOPE_actuator:read)
POST /oauth2/token
Authorization: Basic cHJvbWV0aGV1czpzZWNyZXQ=
Content-Type: application/x-www-form-urlencoded
Host: localhost:8090

grant_type=client_credentials&scope=actuator:read
